version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rasplus
      POSTGRES_USER: rasmoo
      POSTGRES_PASSWORD: qwe123
    ports:
      - 5432:5432
